"""
Subtest: Board SVG Rendering
Stratum: L3_rendering
Purpose: Board SVG matches kicad-cli reference output

Tests that compare our Python SVG output against KiCad CLI reference output.

Test setup:
1. Reference SVGs are generated by kicad-cli (one layer per file)
2. Our Python code generates SVGs using KiCadPcb.to_svg()
3. Tests compare the path data to ensure visual equivalence
"""

import logging
import math
import pytest
import re
import warnings
from pathlib import Path
from typing import List, Set, Tuple
from collections import Counter, defaultdict
from xml.etree import ElementTree as ET

log = logging.getLogger(__name__)

from kicad_monkey.testing.corpus import (
    get_kicad_corpus_case,
    get_kicad_corpus_root,
    iter_kicad_corpus_cases,
    resolve_kicad_manifest_path,
)

OUTPUT_DIR = Path(__file__).parent / "output" / "board_svg"

# Map from legacy single-name fixture identifiers to manifest case_ids.
# Named-fixture tests resolve a specific board via the corpus manifest
# rather than hard-coding directory names — pivoted 2026-05-17 from the
# old ``LEGACY_CASE_MAP`` (directory-name) form.
LEGACY_CASE_IDS: dict[str, str] = {
    "one_via": "synthetic/pcb_foundation/case019__via_basic",
    "one_slot_drill": "synthetic/pcb_foundation/case084__pad_slot_hole",
    "one_zone_filled_top": "synthetic/pcb_foundation/case024__fill_top_zone",
    "board_outline": "synthetic/pcb_foundation/case037__outline_rect",
    "one_custom_pad": "synthetic/pcb_foundation/case122__custom_pad",
    "one_chamfer_roundrect": "synthetic/pcb_foundation/case083__pad_chamfered_roundrect",
    "one_mask_tenting_vias": "synthetic/pcb_foundation/case085__via_mask_tenting",
}


def _legacy_input(legacy_name: str, filename: str) -> Path:
    """Resolve a named-fixture board file path via the corpus manifest."""
    case_id = LEGACY_CASE_IDS.get(legacy_name)
    if case_id is None:
        # Fallback for any future direct case-id usage by name.
        case_id = f"synthetic/pcb_foundation/{legacy_name}"
    case = get_kicad_corpus_case(case_id)
    input_root = resolve_kicad_manifest_path(case, "input_root")
    assert input_root is not None, f"case {case_id} missing input_root"
    return input_root / filename

# Layers to test (matching BOARD_LAYERS from generate_board_svg_references.py)
TEST_LAYERS = [
    "F.Cu",
    "B.Cu",
    "In1.Cu",
    "In2.Cu",
    "F.SilkS",
    "B.SilkS",
    "F.Fab",
    "B.Fab",
    "F.Mask",
    "B.Mask",
    "F.Paste",
    "B.Paste",
    "F.CrtYd",
    "B.CrtYd",
    "Edge.Cuts",
    "User.Drawings",
    "User.Comments",
    "All Layers",  # Combined view
]

# Layers to include in "All Layers" combined view
ALL_LAYERS_LIST = [
    "F.Cu", "B.Cu", "F.SilkS", "B.SilkS", "F.Fab", "B.Fab",
    "F.Mask", "B.Mask", "F.CrtYd", "B.CrtYd", "Edge.Cuts",
    "User.Drawings", "User.Comments",
]


def layer_filename_token(layer: str) -> str:
    """Normalize layer names to the on-disk SVG filename token."""
    return layer.replace(".", "_").replace(" ", "_")


# ============================================================================
# Helper Functions
# ============================================================================

def _iter_board_svg_cases() -> List[dict]:
    """Manifest-driven enumeration of synthetic PCB foundation cases.

    Yields the synthetic ``pcb_foundation`` cases that participate in the
    ``board_svg`` domain. Real-world ``projects/*`` cases also have the
    ``board_svg`` domain but are excluded here pending the legacy
    renderer divergence fix (see KICAD_MONKEY_REWORK_PLAN). Synthetic-only
    scope matches the prior local-glob behaviour exactly.
    """
    cases: list[dict] = []
    for case in iter_kicad_corpus_cases(domain="board_svg"):
        if case.get("origin") != "synthetic":
            continue
        if case.get("layout") != "case_bucket":
            continue
        cases.append(case)
    return cases


def _case_board_path(case: dict) -> Path:
    """Resolve the .kicad_pcb file for a synthetic case_bucket case."""
    input_file = case.get("input_file")
    assert input_file, f"case {case.get('id')} missing input_file"
    return get_kicad_corpus_root() / input_file


def _case_reference_dir(case: dict) -> Path:
    """Resolve the reference_output directory for a case."""
    ref_root = resolve_kicad_manifest_path(case, "reference_output_root")
    assert ref_root is not None, f"case {case.get('id')} missing reference_output_root"
    return ref_root


def get_test_boards() -> List[Path]:
    """Get all PCB foundation board files (manifest-driven)."""
    paths: list[Path] = []
    for case in _iter_board_svg_cases():
        board_path = _case_board_path(case)
        if board_path.exists():
            paths.append(board_path)
    paths.sort()
    return paths


def get_reference_layers_for_board(ref_dir: Path, board_name: str) -> List[str]:
    """Get list of layers that have reference SVGs for a board.

    Args:
        ref_dir: Reference-output directory for the case (resolved via
            the corpus manifest).
        board_name: Internal file basename, e.g. ``one_via`` for
            ``one_via.kicad_pcb`` (distinct from case_id because inner
            files retain their original descriptor names).
    """
    layers = []
    for layer in TEST_LAYERS:
        layer_safe = layer_filename_token(layer)
        ref_path = ref_dir / f"{board_name}__{layer_safe}.svg"
        if ref_path.exists():
            layers.append(layer)
    return layers


def extract_path_coords(path_d: str, precision: int = 2) -> List[Tuple[float, float]]:
    """
    Extract coordinate pairs from SVG path data.

    Handles common SVG path commands:
    - M/m (moveto): 2 coords
    - L/l (lineto): 2 coords
    - H/h (horizontal lineto): 1 coord (x only, skip)
    - V/v (vertical lineto): 1 coord (y only, skip)
    - C/c (curveto): 6 coords (3 points)
    - S/s (smooth curveto): 4 coords (2 points)
    - Q/q (quadratic): 4 coords (2 points)
    - T/t (smooth quadratic): 2 coords
    - A/a (arc): 7 params (rx ry x-rotation large-arc sweep x y) - extract only endpoint
    - Z/z (close path): 0 coords

    Args:
        path_d: SVG path d attribute value
        precision: Decimal places for rounding (default 2 for 0.01mm tolerance)

    Returns list of (x, y) coordinate tuples (not centered, just extracted and rounded).
    """
    coords = []

    # Split path into commands with their parameters
    # Pattern: command letter followed by numbers (possibly with commas/spaces)
    command_pattern = r'([MLHVCSQTAZmlhvcsqtaz])([^MLHVCSQTAZmlhvcsqtaz]*)'

    for match in re.finditer(command_pattern, path_d):
        cmd = match.group(1)
        params_str = match.group(2).strip()

        if not params_str:
            continue

        # Extract all numbers from the parameter string
        numbers = [float(n) for n in re.findall(r'-?\d+\.?\d*', params_str)]

        if cmd.upper() in ('M', 'L', 'T'):
            # MoveTo, LineTo, Smooth Quadratic: pairs of (x, y)
            for i in range(0, len(numbers) - 1, 2):
                coords.append((round(numbers[i], precision), round(numbers[i + 1], precision)))

        elif cmd.upper() == 'H':
            # Horizontal line: single x value - skip (not a full coordinate)
            pass

        elif cmd.upper() == 'V':
            # Vertical line: single y value - skip (not a full coordinate)
            pass

        elif cmd.upper() == 'C':
            # Cubic Bezier: 6 numbers per curve (x1 y1 x2 y2 x y)
            for i in range(0, len(numbers) - 5, 6):
                coords.append((round(numbers[i], precision), round(numbers[i + 1], precision)))
                coords.append((round(numbers[i + 2], precision), round(numbers[i + 3], precision)))
                coords.append((round(numbers[i + 4], precision), round(numbers[i + 5], precision)))

        elif cmd.upper() in ('S', 'Q'):
            # Smooth Cubic or Quadratic: 4 numbers per curve (x2 y2 x y) or (x1 y1 x y)
            for i in range(0, len(numbers) - 3, 4):
                coords.append((round(numbers[i], precision), round(numbers[i + 1], precision)))
                coords.append((round(numbers[i + 2], precision), round(numbers[i + 3], precision)))

        elif cmd.upper() == 'A':
            # Arc: 7 numbers per arc (rx ry x-rotation large-arc sweep x y)
            # Only extract the endpoint (x, y) - last two numbers
            for i in range(0, len(numbers) - 6, 7):
                coords.append((round(numbers[i + 5], precision), round(numbers[i + 6], precision)))

        # Z (close path) has no coordinates

    return coords


def normalize_path_data(path_d: str, precision: int = 2) -> Set[Tuple[float, ...]]:
    """
    Normalize SVG path data to a set of coordinate tuples.

    This allows comparing paths regardless of:
    - Starting point (paths can start at any corner)
    - Whitespace/formatting differences
    - Absolute offset (different bounding box calculations)
    - Minor floating point precision differences

    Args:
        path_d: SVG path d attribute value
        precision: Decimal places for rounding (default 2 for 0.01mm tolerance)

    Returns set of coordinate tuples for comparison, centered at origin.

    NOTE: For comparing multiple paths that may have different viewBox offsets,
    use extract_path_coords() for each path, combine all coords, then center
    the combined set together.
    """
    coords = extract_path_coords(path_d, precision)

    if not coords:
        return set()

    # Center the coordinates at origin to normalize for different bounding boxes
    # This allows comparison even when viewBox offsets differ
    min_x = min(c[0] for c in coords)
    min_y = min(c[1] for c in coords)

    centered = [(round(x - min_x, precision), round(y - min_y, precision)) for x, y in coords]
    return set(centered)


def extract_paths_from_svg(svg_content: str) -> List[str]:
    """Extract all path d= attributes from SVG.

    The negative lookbehind avoids spurious matches against ``data-uuid="..."``
    / ``data-ref="..."`` /``id="..."`` (the IR renderer emits group identity
    attributes whose values contain hex chars that the SVG-path parser would
    mistake for path commands).
    """
    pattern = r'(?<![a-zA-Z\-_])d="([^"]+)"'
    return re.findall(pattern, svg_content)


def extract_polyline_coords_from_svg(
    svg_content: str, precision: int = 2
) -> List[Tuple[float, float]]:
    """Extract coordinates from all <polyline> and <polygon> elements.

    The IR renderer emits stroked segments as ``<polyline>`` and filled
    regions as ``<polygon>``; both carry a ``points="x,y x,y ..."`` attribute.
    """
    coords: List[Tuple[float, float]] = []
    for points_attr in re.findall(
        r'<(?:polyline|polygon)[^>]*\spoints="([^"]+)"', svg_content
    ):
        nums = [float(n) for n in re.findall(r'-?\d+\.?\d*', points_attr)]
        for i in range(0, len(nums) - 1, 2):
            coords.append((round(nums[i], precision), round(nums[i + 1], precision)))
    return coords


def extract_rect_coords_from_svg(
    svg_content: str, precision: int = 2
) -> List[Tuple[float, float]]:
    """Extract corner coordinates from all <rect ...> elements (skipping the
    canvas background rect with fill=#FFFFFF and no stroke)."""
    coords: List[Tuple[float, float]] = []
    rect_pattern = re.compile(r'<rect\b([^/>]*)/?>')
    for attrs in rect_pattern.findall(svg_content):
        # Skip the canvas background rect — it's the page-sized white fill.
        if 'fill="#FFFFFF"' in attrs and 'stroke=' not in attrs:
            continue
        x_match = re.search(r'\sx="([^"]+)"', attrs)
        y_match = re.search(r'\sy="([^"]+)"', attrs)
        w_match = re.search(r'\swidth="([^"]+)"', attrs)
        h_match = re.search(r'\sheight="([^"]+)"', attrs)
        if not (x_match and y_match and w_match and h_match):
            continue
        x = float(x_match.group(1))
        y = float(y_match.group(1))
        w = float(w_match.group(1))
        h = float(h_match.group(1))
        for cx, cy in ((x, y), (x + w, y), (x + w, y + h), (x, y + h)):
            coords.append((round(cx, precision), round(cy, precision)))
    return coords


def extract_line_coords_from_svg(
    svg_content: str, precision: int = 2
) -> List[Tuple[float, float]]:
    """Extract endpoint coordinates from all <line x1=... y1=... x2=... y2=...> elements."""
    coords: List[Tuple[float, float]] = []
    line_pattern = re.compile(
        r'<line\s+[^>]*x1="([^"]+)"\s+y1="([^"]+)"\s+x2="([^"]+)"\s+y2="([^"]+)"'
    )
    for x1, y1, x2, y2 in line_pattern.findall(svg_content):
        coords.append((round(float(x1), precision), round(float(y1), precision)))
        coords.append((round(float(x2), precision), round(float(y2), precision)))
    return coords


_SVG_NS = "http://www.w3.org/2000/svg"


def _parse_translate_transform(transform_attr: str) -> Tuple[float, float]:
    """Return (tx, ty) extracted from a ``transform="translate(x y)"`` value.

    Only the translate primitive is needed today — the IR renderer emits a
    bare ``translate(x y)`` on footprint groups; CLI emits ``translate(0 0)
    scale(1 1)`` on its outer group. ``scale(1 1)`` and ``translate(0 0)``
    contribute nothing, so other transform primitives are ignored.
    """
    if not transform_attr:
        return (0.0, 0.0)
    tx = 0.0
    ty = 0.0
    for match in re.finditer(
        r'translate\(\s*(-?\d+\.?\d*)[ ,]\s*(-?\d+\.?\d*)\s*\)', transform_attr
    ):
        tx += float(match.group(1))
        ty += float(match.group(2))
    return (tx, ty)


SvgMatrix = Tuple[float, float, float, float, float, float]
_IDENTITY_MATRIX: SvgMatrix = (1.0, 0.0, 0.0, 1.0, 0.0, 0.0)


def _mat_mul(left: SvgMatrix, right: SvgMatrix) -> SvgMatrix:
    """Compose two SVG affine matrices."""
    a, b, c, d, e, f = left
    g, h, i, j, k, l = right
    return (
        a * g + c * h,
        b * g + d * h,
        a * i + c * j,
        b * i + d * j,
        a * k + c * l + e,
        b * k + d * l + f,
    )


def _mat_apply(matrix: SvgMatrix, x: float, y: float) -> Tuple[float, float]:
    a, b, c, d, e, f = matrix
    return (a * x + c * y + e, b * x + d * y + f)


def _parse_transform_matrix(transform_attr: str) -> SvgMatrix:
    """Parse translate/rotate/scale/matrix transform-list entries."""
    matrix = _IDENTITY_MATRIX
    if not transform_attr:
        return matrix

    for name, raw_args in re.findall(r'([a-zA-Z]+)\(([^)]*)\)', transform_attr):
        args = [float(n) for n in re.findall(r'-?\d+\.?\d*', raw_args)]
        local = _IDENTITY_MATRIX
        lname = name.lower()
        if lname == "translate" and args:
            tx = args[0]
            ty = args[1] if len(args) > 1 else 0.0
            local = (1.0, 0.0, 0.0, 1.0, tx, ty)
        elif lname == "scale" and args:
            sx = args[0]
            sy = args[1] if len(args) > 1 else sx
            local = (sx, 0.0, 0.0, sy, 0.0, 0.0)
        elif lname == "rotate" and args:
            angle = math.radians(args[0])
            cos_a = math.cos(angle)
            sin_a = math.sin(angle)
            rot = (cos_a, sin_a, -sin_a, cos_a, 0.0, 0.0)
            if len(args) >= 3:
                cx, cy = args[1], args[2]
                local = _mat_mul(
                    _mat_mul((1.0, 0.0, 0.0, 1.0, cx, cy), rot),
                    (1.0, 0.0, 0.0, 1.0, -cx, -cy),
                )
            else:
                local = rot
        elif lname == "matrix" and len(args) >= 6:
            local = (args[0], args[1], args[2], args[3], args[4], args[5])
        matrix = _mat_mul(matrix, local)
    return matrix


def _strip_svg_ns(tag: str) -> str:
    if tag.startswith("{"):
        return tag.split("}", 1)[1]
    return tag


def _shape_coords_with_transform(
    element: ET.Element,
    parent_matrix: SvgMatrix,
    precision: int,
    out: List[Tuple[float, float]],
) -> None:
    """Recursive walk that accumulates translate-transformed coords.

    Skips the canvas background rect (white fill, no stroke).
    """
    tag = _strip_svg_ns(element.tag)
    matrix = _mat_mul(parent_matrix, _parse_transform_matrix(element.get("transform", "")))
    if tag == "g":
        for child in element:
            _shape_coords_with_transform(child, matrix, precision, out)
        return

    def _push(x: float, y: float) -> None:
        px, py = _mat_apply(matrix, x, y)
        out.append((round(px, precision), round(py, precision)))

    if tag == "path":
        d = element.get("d")
        if d:
            for x, y in extract_path_coords(d, precision):
                _push(x, y)
    elif tag in ("polyline", "polygon"):
        pts = element.get("points", "")
        nums = [float(n) for n in re.findall(r'-?\d+\.?\d*', pts)]
        for i in range(0, len(nums) - 1, 2):
            _push(nums[i], nums[i + 1])
    elif tag == "rect":
        fill = element.get("fill", "")
        stroke = element.get("stroke", "")
        # Skip canvas background rect.
        if fill.lower() == "#ffffff" and not stroke:
            return
        try:
            x = float(element.get("x", "0"))
            y = float(element.get("y", "0"))
            w = float(element.get("width", "0"))
            h = float(element.get("height", "0"))
        except ValueError:
            return
        for cx, cy in ((x, y), (x + w, y), (x + w, y + h), (x, y + h)):
            _push(cx, cy)
    elif tag == "line":
        try:
            x1 = float(element.get("x1", "0"))
            y1 = float(element.get("y1", "0"))
            x2 = float(element.get("x2", "0"))
            y2 = float(element.get("y2", "0"))
        except ValueError:
            return
        _push(x1, y1)
        _push(x2, y2)
    # circle/text/etc. — circles are handled separately.

    for child in element:
        _shape_coords_with_transform(child, matrix, precision, out)


def extract_all_shape_coords(
    svg_content: str, precision: int = 2
) -> List[Tuple[float, float]]:
    """Aggregate transform-aware coords from path/polyline/polygon/rect/line.

    The reference SVGs from kicad-cli use ``<path d="...">`` under a top-level
    ``<g transform="translate(0 0) scale(1 1)">``; the IR renderer instead
    uses native ``<polyline>`` / ``<polygon>`` / ``<rect>`` / ``<line>``, with
    ``<g transform="translate(tx ty)">`` wrapping each footprint. This walker
    accumulates the translate components so footprint-local coords end up in
    board coordinates for set-based comparison.

    Falls back to flat regex extraction if SVG parsing fails (unlikely for
    the well-formed CLI/IR output but cheap insurance).
    """
    coords: List[Tuple[float, float]] = []
    try:
        root = ET.fromstring(svg_content)
    except ET.ParseError:
        for path_d in extract_paths_from_svg(svg_content):
            coords.extend(extract_path_coords(path_d, precision))
        coords.extend(extract_polyline_coords_from_svg(svg_content, precision))
        coords.extend(extract_rect_coords_from_svg(svg_content, precision))
        coords.extend(extract_line_coords_from_svg(svg_content, precision))
        return coords

    _shape_coords_with_transform(root, _IDENTITY_MATRIX, precision, coords)
    return coords


def extract_circles_from_svg(svg_content: str) -> List[Tuple[float, float, float]]:
    """Extract all circle elements from SVG as (cx, cy, r) tuples."""
    circles: List[Tuple[float, float, float]] = []

    def _walk(element: ET.Element, parent_matrix: SvgMatrix) -> None:
        matrix = _mat_mul(parent_matrix, _parse_transform_matrix(element.get("transform", "")))
        if _strip_svg_ns(element.tag) == "circle":
            try:
                cx = float(element.get("cx", "0"))
                cy = float(element.get("cy", "0"))
                r = float(element.get("r", "0"))
            except ValueError:
                return
            tx, ty = _mat_apply(matrix, cx, cy)
            circles.append((tx, ty, r))
        for child in element:
            _walk(child, matrix)

    try:
        root = ET.fromstring(svg_content)
    except ET.ParseError:
        pattern = r'<circle\s+cx="([^"]+)"\s+cy="([^"]+)"\s+r="([^"]+)"'
        for match in re.finditer(pattern, svg_content):
            cx = float(match.group(1))
            cy = float(match.group(2))
            r = float(match.group(3))
            circles.append((cx, cy, r))
        return circles

    _walk(root, _IDENTITY_MATRIX)
    return circles


def normalize_circles(circles: List[Tuple[float, float, float]], precision: int = 2) -> Set[Tuple[float, float, float]]:
    """Normalize circle coordinates relative to their bounding box."""
    if not circles:
        return set()

    min_x = min(c[0] - c[2] for c in circles)
    min_y = min(c[1] - c[2] for c in circles)

    return {
        (round(cx - min_x, precision), round(cy - min_y, precision), round(r, precision))
        for cx, cy, r in circles
    }


def count_svg_shapes(svg_content: str) -> dict:
    """Count all shape types in SVG."""
    return {
        'paths': len(extract_paths_from_svg(svg_content)),
        'circles': len(extract_circles_from_svg(svg_content)),
    }


def detect_offset_from_circles(our_circles: List[Tuple[float, float, float]],
                                ref_circles: List[Tuple[float, float, float]]) -> Tuple[float, float]:
    """
    Detect consistent coordinate offset between two SVGs using circle positions.

    Different bounding box calculations can shift all content by a constant offset.
    Circles are ideal for detecting this because they have precise center points
    and unique radii that help match corresponding circles.

    Returns (offset_x, offset_y) to add to our coordinates to match reference.
    """
    if not our_circles or not ref_circles:
        return (0.0, 0.0)

    # Group circles by rounded radius for matching (with tolerance for minor differences)
    def group_by_radius(circles, precision=2):
        groups = {}
        for cx, cy, r in circles:
            r_key = round(r, precision)  # Use 2 decimal places (0.01mm tolerance)
            if r_key not in groups:
                groups[r_key] = []
            groups[r_key].append((cx, cy, r))
        return groups

    our_groups = group_by_radius(our_circles)
    ref_groups = group_by_radius(ref_circles)

    # Find offset from circles with matching radii
    offsets = []
    for r_key in our_groups:
        if r_key not in ref_groups:
            continue
        our_c = our_groups[r_key]
        ref_c = ref_groups[r_key]
        # Only use groups with same count (clear correspondence)
        if len(our_c) != len(ref_c):
            continue
        # Sort by position to match corresponding circles
        our_sorted = sorted(our_c, key=lambda c: (c[0], c[1]))
        ref_sorted = sorted(ref_c, key=lambda c: (c[0], c[1]))
        for i in range(len(our_sorted)):
            dx = ref_sorted[i][0] - our_sorted[i][0]
            dy = ref_sorted[i][1] - our_sorted[i][1]
            offsets.append((round(dx, 4), round(dy, 4)))

    if not offsets:
        return (0.0, 0.0)

    # Find most common offset (mode)
    offset_counts = Counter(offsets)
    most_common = offset_counts.most_common(1)[0]
    # Only use if at least 10 circles agree on this offset, or >50% of samples
    if most_common[1] >= 10 or most_common[1] >= len(offsets) * 0.5:
        return most_common[0]

    return (0.0, 0.0)


def compare_svg_shapes(
    our_svg: str,
    ref_svg: str,
    tolerance: float = 0.5,
    min_match_pct: float = 90.0,
) -> Tuple[bool, str]:
    """
    Compare SVG shapes between our output and reference.

    Handles:
    - Paths (filled polygons and stroked lines)
    - Circles (native circles and via pads)
    - Different grouping structures (KiCad may combine line segments)
    - Different bounding box calculations (detected via circle offset)

    The key insight: KiCad CLI often combines connected line segments into
    single closed paths, while we render each segment separately. But the
    actual coordinates should match when aggregated.

    For boards with zones, we use tolerance-based matching because:
    - KiCad CLI re-computes zone fills during export
    - Stored polygon data may differ from rendered output
    - Thermal reliefs and clearances create coordinate differences

    Args:
        our_svg: Our generated SVG content
        ref_svg: KiCad CLI reference SVG content
        tolerance: Maximum coordinate difference to consider as match (mm)

    Returns (match, message) tuple.
    """
    our_paths = extract_paths_from_svg(our_svg)
    our_circles = extract_circles_from_svg(our_svg)
    ref_paths = extract_paths_from_svg(ref_svg)
    ref_circles = extract_circles_from_svg(ref_svg)

    # Detect coordinate offset between SVGs using circles
    # Different bounding box calculations can shift all content by a constant amount
    offset_x, offset_y = detect_offset_from_circles(our_circles, ref_circles)

    # For circles, compare with offset applied
    def normalize_circles_with_offset(circles, offset_x=0, offset_y=0, precision=2):
        if not circles:
            return set()
        # Apply offset first
        adjusted = [(cx + offset_x, cy + offset_y, r) for cx, cy, r in circles]
        min_x = min(c[0] - c[2] for c in adjusted)
        min_y = min(c[1] - c[2] for c in adjusted)
        return {
            (round(cx - min_x, precision), round(cy - min_y, precision), round(r, precision))
            for cx, cy, r in adjusted
        }

    our_circles_set = normalize_circles_with_offset(our_circles, offset_x, offset_y)
    ref_circles_set = normalize_circles(ref_circles)

    # Allow small circle count differences due to rendering differences
    circle_diff = abs(len(our_circles_set) - len(ref_circles_set))
    circle_diff_pct = circle_diff / max(len(ref_circles_set), 1) * 100 if ref_circles_set else 0

    if circle_diff > 5 and circle_diff_pct > 10:  # More than 5 circles and more than 10% difference
        return False, f"Circle count mismatch: ours={len(our_circles_set)}, ref={len(ref_circles_set)}"

    # For paths, aggregate ALL coordinates from ALL path/polyline/rect/line
    # elements first (without centering). The IR renderer uses native
    # polyline/rect/line elements where kicad-cli uses path-d strings, so
    # extracting only from <path d="..."> would zero out the IR output.
    our_raw_coords = extract_all_shape_coords(our_svg)
    ref_raw_coords = extract_all_shape_coords(ref_svg)

    # Apply offset to our coordinates, then center both coordinate sets.
    # Set semantics intentionally tolerate representation differences:
    # e.g., one closed path vs four stroked edges with shared corner points.
    def center_coords_with_offset(coords: List[Tuple[float, float]], offset_x: float = 0,
                                  offset_y: float = 0, precision: int = 2) -> Set[Tuple[float, float]]:
        if not coords:
            return set()
        # Apply offset first
        adjusted = [(x + offset_x, y + offset_y) for x, y in coords]
        min_x = min(c[0] for c in adjusted)
        min_y = min(c[1] for c in adjusted)
        return {(round(x - min_x, precision), round(y - min_y, precision)) for x, y in adjusted}

    def center_coords(coords: List[Tuple[float, float]], precision: int = 2) -> Set[Tuple[float, float]]:
        if not coords:
            return set()
        min_x = min(c[0] for c in coords)
        min_y = min(c[1] for c in coords)
        return {(round(x - min_x, precision), round(y - min_y, precision)) for x, y in coords}

    def tolerance_match_count(
        ours: Set[Tuple[float, float]],
        refs: Set[Tuple[float, float]],
        tol: float,
    ) -> int:
        """One-to-one greedy coordinate matching within tolerance using spatial bins."""
        if not ours or not refs:
            return 0

        cell = max(tol, 0.01)
        ref_bins = defaultdict(list)
        ref_list = list(refs)
        for idx, (x, y) in enumerate(ref_list):
            ref_bins[(int(x // cell), int(y // cell))].append(idx)

        used_ref = [False] * len(ref_list)
        matches = 0

        for x, y in ours:
            cell_x = int(x // cell)
            cell_y = int(y // cell)
            best_idx = None
            best_dist = None

            for bx in (cell_x - 1, cell_x, cell_x + 1):
                for by in (cell_y - 1, cell_y, cell_y + 1):
                    for idx in ref_bins.get((bx, by), []):
                        if used_ref[idx]:
                            continue

                        rx, ry = ref_list[idx]
                        dx = abs(x - rx)
                        dy = abs(y - ry)
                        if dx > tol or dy > tol:
                            continue

                        dist = dx + dy
                        if best_dist is None or dist < best_dist:
                            best_dist = dist
                            best_idx = idx

            if best_idx is not None:
                used_ref[best_idx] = True
                matches += 1

        return matches

    our_all_coords = center_coords_with_offset(our_raw_coords, offset_x, offset_y)
    ref_all_coords = center_coords(ref_raw_coords)

    if our_all_coords == ref_all_coords:
        return True, (
            f"All shapes match exactly (paths={len(our_paths)}, circles={len(our_circles)}, "
            f"coords={len(our_all_coords)})"
        )

    only_in_ours = our_all_coords - ref_all_coords
    only_in_ref = ref_all_coords - our_all_coords

    # For small differences (likely simple boards), allow minor variations.
    if len(only_in_ours) <= 5 and len(only_in_ref) <= 5:
        return True, (
            f"Shapes match with minor differences ({len(only_in_ours)} extra in ours, "
            f"{len(only_in_ref)} extra in ref)"
        )

    # For larger differences (boards with zones), use tolerance-based matching
    # and compute a match percentage
    tolerance_matches = tolerance_match_count(only_in_ours, only_in_ref, tolerance)

    # Calculate match percentage
    total_coords = max(len(our_all_coords), len(ref_all_coords), 1)
    exact_matches = len(our_all_coords & ref_all_coords)
    total_matched = exact_matches + tolerance_matches
    match_pct = total_matched / total_coords * 100

    # Accept if at least min_match_pct of coordinates match (exact or within tolerance)
    # Zone fills can differ significantly due to KiCad CLI re-computing them at export time
    if match_pct >= min_match_pct:
        return True, f"Shapes match within tolerance ({match_pct:.1f}% match, paths={len(our_paths)}, circles={len(our_circles)})"

    unmatched_ours = max(0, len(only_in_ours) - tolerance_matches)
    unmatched_ref = max(0, len(only_in_ref) - tolerance_matches)

    msg_parts = [f"{match_pct:.1f}% match"]
    if unmatched_ours:
        msg_parts.append(f"{unmatched_ours} coords only in ours")
    if unmatched_ref:
        msg_parts.append(f"{unmatched_ref} coords only in ref")

    return False, (
        f"Coordinate mismatch: {', '.join(msg_parts)} "
        f"(ours={len(our_all_coords)}, ref={len(ref_all_coords)})"
    )


# ============================================================================
# Test Cases Discovery
# ============================================================================

def get_test_cases() -> List[Tuple[Path, str]]:
    """Get all (board_path, layer) test case tuples (manifest-driven)."""
    test_cases = []
    for case in _iter_board_svg_cases():
        board_path = _case_board_path(case)
        if not board_path.exists():
            continue
        ref_dir = _case_reference_dir(case)
        if not ref_dir.exists():
            continue
        board_name = board_path.stem
        for layer in get_reference_layers_for_board(ref_dir, board_name):
            test_cases.append((board_path, layer))
    test_cases.sort(key=lambda pair: (pair[0].as_posix(), pair[1]))
    return test_cases


def _make_test_id(test_case: Tuple[Path, str]) -> str:
    """Generate test ID for a test case."""
    board_path, layer = test_case
    return f"{board_path.stem}__{layer_filename_token(layer)}"


# Known failing tests to skip - format: (board_name, layer)
SKIP_TESTS: set[tuple[str, str]] = set()


# Real-world layers with KiCad-equivalent geometry but noisy coordinate-level
# text tessellation or stale pre-knockout reference SVGs. Keep these explicit
# so broad skips cannot hide regressions.
MATCH_THRESHOLDS: dict[tuple[str, str], float] = {
    ("missing_elements", "*"): 85.0,
    ("speedy", "F.SilkS"): 80.0,
    ("11-10043__charge_indicator__C", "B.Fab"): 85.0,
    ("11-10045__taillight__C", "F.SilkS"): 80.0,
}


def match_threshold_for(board_name: str, layer: str) -> float:
    """Return the minimum coordinate match threshold for a board layer."""
    return MATCH_THRESHOLDS.get((board_name, layer), MATCH_THRESHOLDS.get((board_name, "*"), 90.0))


# ============================================================================
# Test Classes
# ============================================================================

class TestBoardSvgGeneration:
    """Tests for board SVG generation."""

    def test_simple_board_generates_svg(self):
        """Test that a simple board generates valid SVG."""
        from kicad_monkey import KiCadPcb

        # Use a simple test board
        board_files = get_test_boards()
        if not board_files:
            pytest.skip("No test boards available")

        pcb = KiCadPcb.from_file(board_files[0])
        svg = pcb.to_svg(layers=["F.Cu"])

        assert svg is not None
        assert "<?xml version" in svg
        assert "<svg" in svg
        assert "</svg>" in svg

    def test_layer_filter_works(self):
        """Test that layer filter only includes requested layers."""
        from kicad_monkey import KiCadPcb

        board_files = get_test_boards()
        if not board_files:
            pytest.skip("No test boards available")

        pcb = KiCadPcb.from_file(board_files[0])

        # Generate SVG for single layer
        svg_fcu = pcb.to_svg(layers=["F.Cu"])
        svg_bcu = pcb.to_svg(layers=["B.Cu"])

        # Both should be valid SVGs
        assert "<svg" in svg_fcu
        assert "<svg" in svg_bcu

    def test_render_path_emits_no_deprecation_warnings(self):
        """Standard PCB SVG render path should be free of DeprecationWarning."""
        from kicad_monkey import KiCadPcb

        board_path = _legacy_input("one_via", "one_via.kicad_pcb")
        if not board_path.exists():
            pytest.skip(f"Input not found: {board_path}")

        pcb = KiCadPcb.from_file(board_path)

        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            svg = pcb.to_svg(layers=["F.Cu"])

        assert "<svg" in svg
        deprecations = [w for w in caught if issubclass(w.category, DeprecationWarning)]
        assert not deprecations, (
            "DeprecationWarning emitted in standard render path: "
            + "; ".join(str(w.message) for w in deprecations)
        )

    def test_layers_none_matches_explicit_all_layers_drill_semantics(self):
        """layers=None should include the same drill semantics as explicit all-layers."""
        from kicad_monkey import KiCadPcb

        board_path = _legacy_input("one_via", "one_via.kicad_pcb")
        if not board_path.exists():
            pytest.skip(f"Input not found: {board_path}")

        pcb = KiCadPcb.from_file(board_path)
        svg_default = pcb.to_svg()
        explicit_layers = [layer for layer in TEST_LAYERS if layer != "All Layers"]
        svg_explicit = pcb.to_svg(layers=explicit_layers)

        def white_drill_bucket_count(svg: str) -> int:
            return sum(
                1
                for style in re.findall(r'<g style="([^"]*)"', svg, flags=re.IGNORECASE)
                if "fill:#ffffff" in style.lower() and "stroke:none" in style.lower()
            )

        default_white_groups = white_drill_bucket_count(svg_default)
        explicit_white_groups = white_drill_bucket_count(svg_explicit)

        assert explicit_white_groups > 0, "Expected at least one white drill overlay in explicit all-layer view"
        assert default_white_groups == explicit_white_groups, (
            f"layers=None drill semantics mismatch: default={default_white_groups}, "
            f"explicit={explicit_white_groups}"
        )

    def test_oval_drill_renders_slot_geometry(self):
        """Oval drills should render as slot geometry, not a circle fallback."""
        from kicad_monkey import KiCadPcb

        board_path = _legacy_input("one_slot_drill", "one_slot_drill.kicad_pcb")
        if not board_path.exists():
            pytest.skip(f"Input not found: {board_path}")

        pcb = KiCadPcb.from_file(board_path)
        svg_copper = pcb.to_svg(layers=["F.Cu"])
        svg_edge = pcb.to_svg(layers=["Edge.Cuts"])

        # Copper drill overlay should include a white stroked slot centerline (CLI parity).
        assert (
            re.search(r"stroke:#FFFFFF;\s*stroke-width:1\.0000;[^>]*>\s*<path d=\"M", svg_copper)
            or re.search(r'<polyline[^>]*stroke="#FFFFFF"[^>]*stroke-width="1"', svg_copper)
        ), (
            "Expected white stroked slot drill path on copper export"
        )

        # Non-copper layers should show slot drill as a black stroked slot centerline.
        assert (
            re.search(r"stroke:#000000;\s*stroke-width:1\.0000;[^>]*>\s*<path d=\"M", svg_edge)
            or re.search(r'<polyline[^>]*stroke="#000000"[^>]*stroke-width="1"', svg_edge)
        ), (
            "Expected black stroked slot drill path on non-copper export"
        )

    def test_custom_pad_gr_poly_primitives_render_without_skip_warning(self):
        """Custom pad gr_poly primitives should render through explicit OOP data."""
        from kicad_monkey import KiCadPcb
        import warnings

        board_path = _legacy_input("one_custom_pad", "one_custom_pad.kicad_pcb")
        if not board_path.exists():
            pytest.skip(f"Input not found: {board_path}")

        pcb = KiCadPcb.from_file(board_path)

        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            svg_copper = pcb.to_svg(layers=["F.Cu"])

        custom_pad_warnings = [
            w for w in caught
            if issubclass(w.category, RuntimeWarning) and "Pad shape 'custom'" in str(w.message)
        ]
        assert not custom_pad_warnings, "Custom pad should not be skipped when primitives are present"

        # one_custom_pad has only a custom copper pad on F.Cu; it may be
        # represented as a path by the legacy renderer or as native polygon/
        # polyline elements by the IR renderer.
        assert re.search(r"<(?:path|polygon|polyline)\b", svg_copper)

    def test_chamfer_roundrect_pad_renders_chamfer_polygon(self):
        """Chamfered roundrect pads should not collapse to a 4-corner rectangle."""
        from kicad_monkey import KiCadPcb

        board_path = _legacy_input("one_chamfer_roundrect", "one_chamfer_roundrect.kicad_pcb")
        if not board_path.exists():
            pytest.skip(f"Input not found: {board_path}")

        pcb = KiCadPcb.from_file(board_path)
        svg_copper = pcb.to_svg(layers=["F.Cu"])
        coords = extract_all_shape_coords(svg_copper, precision=4)
        assert coords, "Expected at least one shape in F.Cu output"

        # A fully chamfered 4-corner pad should emit an octagon-like outline (>=8 points).
        unique_coords = set(coords)
        assert len(unique_coords) >= 8, (
            f"Expected chamfer polygon (>=8 unique points), got {len(unique_coords)}"
        )

    def test_mask_layer_renders_only_exposed_tenting_none_vias(self):
        """Mask view should emit via openings only for vias with explicit (tenting (front no) (back no)).

        KiCad's modern per-via tenting override uses nested ``(front yes/no)`` /
        ``(back yes/no)`` syntax. A side value of ``no`` = explicitly NOT tented
        (mask opening). Legacy ``(tenting none)`` and bare-flag forms collapse
        to "no override → use board default" in current kicad-cli; the fixture
        was migrated to modern syntax 2026-05-10 to match.
        """
        from kicad_monkey import KiCadPcb
        import xml.etree.ElementTree as ET

        board_path = _legacy_input("one_mask_tenting_vias", "one_mask_tenting_vias.kicad_pcb")
        if not board_path.exists():
            pytest.skip(f"Input not found: {board_path}")

        pcb = KiCadPcb.from_file(board_path)
        svg_mask = pcb.to_svg(layers=["B.Mask"])

        # ElementTree cannot parse the SVG doctype directly.
        svg_xml = svg_mask.replace(
            '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" ', ""
        ).replace(' "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"> ', "")
        root = ET.fromstring(svg_xml)
        ns = {"svg": "http://www.w3.org/2000/svg"}
        parent = {child: p for p in root.iter() for child in p}

        black_035 = 0
        white_015 = 0
        for circle in root.findall(".//svg:circle", ns):
            style = (parent.get(circle).get("style") or "").lower()
            r = round(float(circle.get("r")), 4)
            if "fill:#000000" in style and r == 0.3500:
                black_035 += 1
            if "fill:#ffffff" in style and r == 0.1500:
                white_015 += 1

        # one_mask_tenting_vias has two vias of the same geometry:
        # - one default-tented via (no per-via override → hidden on mask)
        # - one explicit (tenting (front no) (back no)) via (visible on mask)
        assert black_035 == 1, f"Expected 1 exposed via mask opening, got {black_035}"
        assert white_015 == 1, f"Expected 1 exposed via drill overlay, got {white_015}"

    def test_black_and_white_true_forces_monochrome_output(self):
        """black_and_white=True should override custom fill/stroke colors."""
        from kicad_monkey import KiCadPcb

        board_path = _legacy_input("one_via", "one_via.kicad_pcb")
        if not board_path.exists():
            pytest.skip(f"Input not found: {board_path}")

        pcb = KiCadPcb.from_file(board_path)
        svg = pcb.to_svg(
            layers=["F.Cu", "Edge.Cuts"],
            fill="#12AB34",
            stroke="#56CD78",
            black_and_white=True,
        )

        assert "#12AB34" not in svg
        assert "#56CD78" not in svg
        assert "fill:#000000" in svg
        assert "stroke:#000000" in svg

    def test_black_and_white_false_honors_custom_colors(self):
        """black_and_white=False should honor custom fill/stroke colors."""
        from kicad_monkey import KiCadPcb

        board_path = _legacy_input("one_via", "one_via.kicad_pcb")
        if not board_path.exists():
            pytest.skip(f"Input not found: {board_path}")

        pcb = KiCadPcb.from_file(board_path)
        svg = pcb.to_svg(
            layers=["F.Cu", "Edge.Cuts"],
            fill="#12AB34",
            stroke="#56CD78",
            black_and_white=False,
        )

        assert "fill:#12AB34" in svg or 'fill="#12AB34"' in svg
        assert "stroke:#56CD78" in svg or 'stroke="#56CD78"' in svg

    def test_charge_indicator_npth_holes_render_as_board_apertures(self):
        """NPTH pads render as holes on non-mask layers and expanded mask openings."""
        from kicad_monkey import KiCadPcb

        case = get_kicad_corpus_case("real_world/charge_indicator")
        input_root = resolve_kicad_manifest_path(case, "input_root")
        assert input_root is not None, "charge_indicator case missing input_root"
        board_path = input_root / "11-10043__charge_indicator__C.kicad_pcb"
        if not board_path.exists():
            pytest.skip(f"Input not found: {board_path}")

        pcb = KiCadPcb.from_file(board_path)

        silk_radii = Counter(round(r, 4) for _, _, r in extract_circles_from_svg(
            pcb.to_svg(layers=["F.SilkS", "Edge.Cuts"])
        ))
        mask_radii = Counter(round(r, 4) for _, _, r in extract_circles_from_svg(
            pcb.to_svg(layers=["F.Mask", "Edge.Cuts"])
        ))

        assert silk_radii[1.25] == 8
        assert mask_radii[1.25] == 8
        assert mask_radii[1.3516] == 8


class TestBoardSvgComparison:
    """Tests comparing our SVG output against KiCad CLI references."""

    @pytest.fixture
    def ensure_output_dir(self):
        """Ensure output directory exists."""
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        return OUTPUT_DIR

    @pytest.mark.parametrize("test_case", get_test_cases(), ids=_make_test_id)
    def test_layer_matches_reference(self, test_case, ensure_output_dir):
        """Test that layer SVG matches reference."""
        from kicad_monkey import KiCadPcb

        board_path, layer = test_case
        board_name = board_path.stem
        # board_path: <input_root>/<descriptor>.kicad_pcb; case folder is
        # the parent of input_root (case_bucket layout).
        board_folder = board_path.parent.parent.name
        layer_safe = layer_filename_token(layer)

        # Skip known failing tests
        if (board_name, layer) in SKIP_TESTS:
            pytest.skip(f"Known issue: {board_name} {layer}")

        # Load board
        pcb = KiCadPcb.from_file(board_path)

        # Reference SVG lives alongside the input: <case>/reference_output/<descriptor>__<layer>.svg.
        ref_path = board_path.parent.parent / "reference_output" / f"{board_name}__{layer_safe}.svg"
        if not ref_path.exists():
            pytest.skip(f"No reference SVG for {board_name} {layer}")
        ref_svg = ref_path.read_text()
        if not ref_svg.strip():
            pytest.skip(f"Empty reference SVG for {board_name} {layer}")

        # Determine layers to render
        if layer == "All Layers":
            # Render all visible layers combined
            layers_to_render = ALL_LAYERS_LIST
        else:
            # For individual layers, include Edge.Cuts for reference
            layers_to_render = [layer]
            if layer != "Edge.Cuts":
                layers_to_render.append("Edge.Cuts")

        # Generate our SVG
        our_svg = pcb.to_svg(layers=layers_to_render)

        # Save our output for debugging in matching subfolder
        out_folder = ensure_output_dir / board_folder
        out_folder.mkdir(parents=True, exist_ok=True)
        out_path = out_folder / f"{board_name}__{layer_safe}.svg"
        out_path.write_text(our_svg)

        # Compare shapes with tighter default threshold and only explicit
        # lower gates for documented real-world text tessellation noise.
        min_match_pct = match_threshold_for(board_name, layer)
        match, msg = compare_svg_shapes(our_svg, ref_svg, min_match_pct=min_match_pct)

        if not match:
            log.error(f"SVG mismatch for {board_name} {layer}: {msg}")
            log.error(f"Our output: {out_path}")
            log.error(f"Reference: {ref_path}")

        assert match, f"SVG mismatch for {board_name} {layer}: {msg}"


# ============================================================================
# Run tests standalone
# ============================================================================

if __name__ == "__main__":
    pytest.main([__file__, "-v"])
