"""
Subtest: Footprint SVG Rendering
Stratum: L3_rendering
Purpose: Footprint SVG matches kicad-cli reference output

Tests that compare our Python SVG output against KiCad CLI reference output.

Test setup:
1. Reference SVGs are generated by kicad-cli (one layer per file)
2. Our Python code generates SVGs using KiCadFootprint.to_svg()
3. Tests compare the path data to ensure visual equivalence
"""

import logging
import pytest
import re
from collections import Counter
from pathlib import Path
from typing import List, Set, Tuple

log = logging.getLogger(__name__)

from conftest import FOOTPRINT_SVG_DIR

# Test case directories
INPUT_DIR = FOOTPRINT_SVG_DIR / "input"
REFERENCE_DIR = FOOTPRINT_SVG_DIR / "reference_output"
OUTPUT_DIR = Path(__file__).parent / "output" / "footprint_svg"

# Layers to test
TEST_LAYERS = ["F.Cu", "B.Cu", "F.SilkS", "B.SilkS", "F.Fab", "B.Fab", "F.Mask", "B.Mask"]


# ============================================================================
# Helper Functions
# ============================================================================

def get_test_footprints() -> List[Path]:
    """Get all footprint files in input directory."""
    if not INPUT_DIR.exists():
        return []
    return sorted(INPUT_DIR.glob("*.kicad_mod"))


def normalize_path_data(path_d: str, precision: int = 2) -> Set[Tuple[float, ...]]:
    """
    Normalize SVG path data to a set of coordinate tuples.

    This allows comparing paths regardless of:
    - Starting point (paths can start at any corner)
    - Whitespace/formatting differences
    - Absolute offset (different bounding box calculations)
    - Minor floating point precision differences

    Args:
        path_d: SVG path d attribute value
        precision: Decimal places for rounding (default 2 for 0.01mm tolerance)

    Returns set of coordinate tuples for comparison, centered at origin.
    """
    # Extract all coordinates from path
    coords = []
    # Match numbers (including negative and decimal)
    numbers = re.findall(r'-?\d+\.?\d*', path_d)
    for i in range(0, len(numbers) - 1, 2):
        x = float(numbers[i])
        y = float(numbers[i + 1])
        coords.append((x, y))

    if not coords:
        return set()

    # Center the coordinates at origin to normalize for different bounding boxes
    # This allows comparison even when viewBox offsets differ
    min_x = min(c[0] for c in coords)
    min_y = min(c[1] for c in coords)

    centered = [(round(x - min_x, precision), round(y - min_y, precision)) for x, y in coords]
    return set(centered)


def extract_paths_from_svg(svg_content: str) -> List[str]:
    """Extract path-like coordinate streams from SVG."""
    paths = re.findall(r'<path\b[^>]*\sd="([^"]+)"', svg_content)
    point_shapes = re.findall(r'<(?:polygon|polyline)\b[^>]*\spoints="([^"]+)"', svg_content)
    return paths + point_shapes


def extract_circles_from_svg(svg_content: str) -> List[Tuple[float, float, float]]:
    """Extract all circle elements from SVG as (cx, cy, r) tuples."""
    circles = []
    # Match circle elements
    pattern = r'<circle\s+cx="([^"]+)"\s+cy="([^"]+)"\s+r="([^"]+)"'
    for match in re.finditer(pattern, svg_content):
        cx = float(match.group(1))
        cy = float(match.group(2))
        r = float(match.group(3))
        circles.append((cx, cy, r))
    return circles


def count_svg_shapes(svg_content: str) -> dict:
    """Count all shape types in SVG."""
    return {
        'paths': len(extract_paths_from_svg(svg_content)),
        'circles': len(extract_circles_from_svg(svg_content)),
    }


def compare_svg_paths(our_svg: str, ref_svg: str) -> Tuple[bool, str]:
    """
    Compare SVG shapes between our output and reference.

    Handles:
    - Paths (our filled polygons and stroked lines)
    - Circles (KiCad native circles)
    - Our circle polygons vs KiCad native circles

    Returns (match, message) tuple.
    """
    our_paths = extract_paths_from_svg(our_svg)
    our_circles = extract_circles_from_svg(our_svg)
    ref_paths = extract_paths_from_svg(ref_svg)
    ref_circles = extract_circles_from_svg(ref_svg)

    # Total shape count (we render circles as paths, KiCad uses native circles)
    our_total = len(our_paths) + len(our_circles)
    ref_total = len(ref_paths) + len(ref_circles)

    # If reference has circles and we have equivalent number of polygon paths,
    # that's acceptable (we render circles as polygon approximations)
    if ref_circles and not our_circles:
        # Check if our extra paths could be circle approximations
        expected_paths = len(ref_paths)
        circle_equivalent_paths = len(ref_circles)
        if len(our_paths) == expected_paths + circle_equivalent_paths:
            # Assume our extra paths are circle approximations - this is OK
            our_paths = our_paths[:expected_paths]  # Compare only the non-circle paths

    if len(our_paths) != len(ref_paths):
        return False, f"Path count mismatch: ours={len(our_paths)}, ref={len(ref_paths)} (circles: ours={len(our_circles)}, ref={len(ref_circles)})"

    our_path_keys = Counter(
        tuple(sorted(normalize_path_data(path)))
        for path in our_paths
    )
    ref_path_keys = Counter(
        tuple(sorted(normalize_path_data(path)))
        for path in ref_paths
    )
    if our_path_keys != ref_path_keys:
        return False, f"Path coords mismatch:\n  ours: {our_path_keys}\n  ref: {ref_path_keys}"

    if len(our_circles) != len(ref_circles):
        return False, f"Circle count mismatch: ours={len(our_circles)}, ref={len(ref_circles)}"

    return True, "All paths match"


# ============================================================================
# Test Classes
# ============================================================================

class TestFootprintSvgGeneration:
    """Tests for footprint SVG generation."""

    def test_simple_footprint_generates_svg(self):
        """Test that a simple footprint generates valid SVG."""
        from kicad_monkey import KiCadFootprint

        # Use a simple test footprint
        fp_files = get_test_footprints()
        if not fp_files:
            pytest.skip("No test footprints available")

        fp = KiCadFootprint.from_file(fp_files[0])
        svg = fp.to_svg(layers=["F.Cu"])

        assert svg is not None
        assert "<?xml version" in svg
        assert "<svg" in svg
        assert "</svg>" in svg

    def test_layer_filter_works(self):
        """Test that layer filter only includes requested layers."""
        from kicad_monkey import KiCadFootprint

        fp_files = get_test_footprints()
        if not fp_files:
            pytest.skip("No test footprints available")

        fp = KiCadFootprint.from_file(fp_files[0])

        # Generate SVG for single layer
        svg_fcu = fp.to_svg(layers=["F.Cu"])
        svg_bcu = fp.to_svg(layers=["B.Cu"])

        # Both should be valid SVGs
        assert "<svg" in svg_fcu
        assert "<svg" in svg_bcu


class TestFootprintSvgComparison:
    """Tests comparing our SVG output against KiCad CLI references."""

    @pytest.fixture
    def ensure_output_dir(self):
        """Ensure output directory exists."""
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        return OUTPUT_DIR

    @pytest.mark.parametrize("fp_path", get_test_footprints(),
                             ids=lambda p: p.stem)
    def test_fcu_layer_matches_reference(self, fp_path, ensure_output_dir):
        """Test that F.Cu layer SVG matches reference."""
        from kicad_monkey import KiCadFootprint

        layer = "F.Cu"
        layer_safe = layer.replace(".", "_")

        # Load footprint
        fp = KiCadFootprint.from_file(fp_path)

        # Check if reference exists
        ref_path = REFERENCE_DIR / f"{fp.name}__{layer_safe}.svg"
        if not ref_path.exists():
            pytest.fail(
                f"Missing reference SVG for {fp.name} {layer}: {ref_path}. "
                "Run tools/kicad/tests/generate_svg_references.py to regenerate references."
            )

        # Generate our SVG
        our_svg = fp.to_svg(layers=[layer])

        # Save our output for debugging
        out_path = ensure_output_dir / f"{fp.name}__{layer_safe}.svg"
        out_path.write_text(our_svg)

        # Load reference
        ref_svg = ref_path.read_text()

        # Compare paths
        match, msg = compare_svg_paths(our_svg, ref_svg)

        if not match:
            log.error(f"SVG mismatch for {fp.name} {layer}: {msg}")
            log.error(f"Our output: {out_path}")
            log.error(f"Reference: {ref_path}")

        assert match, f"SVG mismatch for {fp.name} {layer}: {msg}"


class TestPathNormalization:
    """Tests for path normalization utilities."""

    def test_normalize_simple_rect(self):
        """Test normalizing a simple rectangle path."""
        path1 = "M 0,0 L 1,0 L 1,1 L 0,1 Z"
        path2 = "M 1,1 L 0,1 L 0,0 L 1,0 Z"  # Same rect, different start

        coords1 = normalize_path_data(path1)
        coords2 = normalize_path_data(path2)

        # Both should have same coordinate set
        assert coords1 == coords2

    def test_normalize_with_decimals(self):
        """Test normalizing path with decimal coordinates."""
        path = "M 0.6600,0.7400 0.0000,0.7400 0.0000,0.0000 0.6600,0.0000 Z"
        coords = normalize_path_data(path)

        expected = {(0.66, 0.74), (0.0, 0.74), (0.0, 0.0), (0.66, 0.0)}
        assert coords == expected


# ============================================================================
# Run tests standalone
# ============================================================================

if __name__ == "__main__":
    pytest.main([__file__, "-v"])
